#!/bin/bash
# Family Login v1 - Manual Testing Script
# Run this after applying the migration to production

echo "======================================"
echo "Family Login v1 - Manual Test Script"
echo "======================================"
echo ""
echo "Prerequisites:"
echo "1. Migration 20260914_family_access.sql applied to production"
echo "2. At least one athlete in the system"
echo "3. Admin account logged in to Supabase Dashboard"
echo ""

echo "======================================"
echo "TEST 1: Invite Family Member"
echo "======================================"
echo "1. Log in as admin coach"
echo "2. Navigate to any athlete detail page"
echo "3. Scroll to 'Family Access' section"
echo "4. Enter a test email (e.g., parent+test@example.com)"
echo "5. Click 'Invite'"
echo ""
echo "Expected Result:"
echo "- Success message: 'Invitation sent to parent+test@example.com'"
echo "- Magic link email sent to that address"
echo "- Email appears in 'Current Family Access' list"
echo ""
read -p "Press Enter when ready to continue..."
echo ""

echo "======================================"
echo "TEST 2: Family Login & Routing"
echo "======================================"
echo "1. Open magic link from invitation email"
echo "2. Click the link (or paste in browser)"
echo ""
echo "Expected Result:"
echo "- User is logged in automatically"
echo "- Redirected to athlete detail page (NOT roster)"
echo "- Can see athlete profile: name, belt, tokui-waza, opponent notes"
echo "- 'Edit' button is visible"
echo ""
read -p "Press Enter when ready to continue..."
echo ""

echo "======================================"
echo "TEST 3: Family Can Edit Safe Fields"
echo "======================================"
echo "1. As family user, click 'Edit' on athlete page"
echo "2. Modify tokui-waza notes or development areas"
echo "3. Click 'Save Changes'"
echo ""
echo "Expected Result:"
echo "- Changes saved successfully"
echo "- Page refreshes with updated values"
echo "- Coach assignment section shows as read-only"
echo ""
read -p "Press Enter when ready to continue..."
echo ""

echo "======================================"
echo "TEST 4: Family CANNOT Access Other Athletes"
echo "======================================"
echo "1. As family user, manually navigate to:"
echo "   /athletes/[different-athlete-id]"
echo "   (Use an athlete ID that family is NOT linked to)"
echo ""
echo "Expected Result:"
echo "- Redirected to /unauthorized"
echo "- Message: 'Access Not Authorized'"
echo "- Cannot see other athlete's data"
echo ""
read -p "Press Enter when ready to continue..."
echo ""

echo "======================================"
echo "TEST 5: Family CANNOT Access Roster"
echo "======================================"
echo "1. As family user, manually navigate to: /"
echo ""
echo "Expected Result:"
echo "- Page shows empty roster (no athletes visible)"
echo "- OR redirected to their athlete page"
echo "- Family cannot see list of other athletes"
echo ""
read -p "Press Enter when ready to continue..."
echo ""

echo "======================================"
echo "TEST 6: Family CANNOT Access Coach Pages"
echo "======================================"
echo "1. As family user, manually navigate to:"
echo "   - /invite (invite coaches)"
echo "   - /tournament-day (tournament assignment)"
echo ""
echo "Expected Result:"
echo "- Both pages redirect to /unauthorized"
echo "- OR show empty state / no access message"
echo ""
read -p "Press Enter when ready to continue..."
echo ""

echo "======================================"
echo "TEST 7: Revoke Family Access"
echo "======================================"
echo "1. Log in as admin coach"
echo "2. Navigate to athlete detail page"
echo "3. Find family email in 'Current Family Access' list"
echo "4. Click 'Revoke'"
echo "5. Confirm revocation"
echo ""
echo "Expected Result:"
echo "- Success message: 'Access revoked for [email]'"
echo "- Email removed from list"
echo "- Family user immediately loses access"
echo ""
read -p "Press Enter when ready to continue..."
echo ""

echo "======================================"
echo "TEST 8: Revoked Family Cannot Login"
echo "======================================"
echo "1. As revoked family user, try to access athlete page"
echo "2. OR log out and log back in"
echo ""
echo "Expected Result:"
echo "- Redirected to /unauthorized"
echo "- OR login succeeds but athlete page shows unauthorized"
echo ""
read -p "Press Enter when ready to continue..."
echo ""

echo "======================================"
echo "TEST 9: Coach Access Unchanged"
echo "======================================"
echo "1. Log in as coach (existing coach_allowlist user)"
echo "2. Navigate to home page (/)"
echo ""
echo "Expected Result:"
echo "- Full roster visible (all athletes)"
echo "- Can access any athlete detail page"
echo "- Can edit, delete, manage coach assignments"
echo "- All existing coach functionality works"
echo ""
read -p "Press Enter when ready to continue..."
echo ""

echo "======================================"
echo "All Tests Complete!"
echo "======================================"
echo ""
echo "Summary:"
echo "✅ Family can log in and see ONLY their linked athlete"
echo "✅ Family can edit safe fields (tokui-waza, ne-waza, notes)"
echo "✅ Family CANNOT see other athletes"
echo "✅ Family CANNOT access coach-only pages"
echo "✅ Admin can invite and revoke family access"
echo "✅ Coach access unchanged"
echo ""
echo "If all tests pass, the feature is ready for production use."
echo ""
